---
# tasks file for roles/redis
- name: Coping Redis Repo  
  ansible.builtin.copy:                    # Copies the file from the files directory
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Installing {{COMPONENT}} package
  ansible.builtin.package:
    name: redis-6.2.13
    state: present 

- name: Restarting service 
  ansible.builtin.service:
    name: "{{COMPONENT}}"
    state: started
    enabled: true  

- name: Updating Config
  ansible.builtin.replace:
    path: /etc/{{COMPONENT}}/{{COMPONENT}}.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0' 
  notify: Restarting service 


- name: set-hostname
  ansible.builtin.shell: sudo set-hostname {{COMPONENT}} 
