- name: Demo on using variables   
  hosts: all
  vars:                                    # Delcaring variables at play level; All tasks of the play can access this variable URL 
    URL: play.google.com 
  vars_files:
    - demo-vars.txt
  # vars_prompt:
  #   - name: URL 
  #     prompt: Enter URL Value 
  #     private: false
    
  tasks: 
    - name: Printing URL 
      ansible.builtin.debug:
        msg: "{{URL}}"

    - name: Printing URLs 
      ansible.builtin.debug:
        msg: value of URL is {{URL}} 
      vars:                               # Declaring the variable at task level ( Local variable )
        URL: hotstar.com

    # - name: Printing CLI_URL 
    #   ansible.builtin.debug:
    #     msg: value of CLI_URL is {{CLI_URL}}