---
- name: Ansible playbook to copy a file
  hosts: all
  become: true
  tasks:
  - name: copy a file
    ansible.builtin.copy:
      src: /home/ansadmin/Ansible2024/index.html
      dest: /home/ansadmin/sampledir/index.html
      owner: jhon
      group: jhon
      mode: '0644'