---
- name: This playbook installs packages using yum
  hosts: dev
  become: true

  tasks:
  - name: Install the latest version of Apache
    ansible.builtin.yum:
      name: httpd
      state: latest
    ansible.builtin.service:
      name: httpd
      state: started

