---
- hosts: all
  become: yes
  become_user: root

  tasks:
  - name: Ensure Nginx is at the latest version
    apt:
      update_cache: true
      name: nginx
      state: latest
  - name: Make sure Nginx is runnning
    systemd:
      state: started
      name: nginx
