---
- name: This playbook installs packages using yum
  hosts: dev
  become: true
  vars: 
    portsa: 8081

  tasks:
  - name: Install the latest version of Apache
    ansible.builtin.yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    notify: make sure to start the service


  - name: copy a file
    ansible.builtin.copy:
      src: //home/ansadmin/Ansible2024/index.html
      dest: /var/www/html
      mode: '0666'

  - name: Ensure the default Apache port is {{ portsa }}
    ansible.builtin.lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: Listen {{ portsa }}
    when: ansible_os_family == "RedHat"
    notify: make sure to start the service


  handlers:
  - name: make sure to start the service
    ansible.builtin.service:
      name: httpd
      state: started
