- name: Demo on facts   
  hosts: all 
  tasks: 
    - name: task1 
      ansible.builtin.debug:
        msg: OS Distribution = {{ansible_distribution}}

    - name: printing mac address 
      ansible.builtin.debug:
        msg: Mac address is {{ansible_default_ipv4.macaddress}}

    - name: printing maarchitecure 
      ansible.builtin.debug:
        msg: architecure is {{ansible_architecture}}

    - name: printing os fAMILY 
      ansible.builtin.debug:
        msg: architecure is {{ansible_os_family}}