---
- name: This playbook installs packages using yum
  hosts: dev
  become: true

  tasks:
  - name: Make sure to stop  the service
    ansible.builtin.service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"
  - name: UnInstall the latest version of Apache
    ansible.builtin.yum:
      name: httpd
      state: removed
    when: ansible_os_family == "RedHat"
